steps:
  - name: gcr.io/cloud-builders/docker
    args: ['info']

  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c',
      - 'echo $DOCKER_OPTS'

  # 1. pull using images before build
  # - name: gcr.io/cloud-builders/docker
  #   args: ['pull', 'alpine:3.12.0']

  - name: gcr.io/cloud-builders/docker
    dir: $_DIR
    args: ['build', '.']

  - name: 'docker/compose:1.26.2'
    dir: $_DIR
    args: ['-f', 'docker-compose.yaml', 'build']

options:
  env:
    - DOCKER_BUILDKIT=1
    - COMPOSE_DOCKER_CLI_BUILD=1

substitutions:
  _DIR: buildkit
