steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: $_DIR
    args: ['build', '-t', 'build-in-host:latest', '.']

  - name: 'docker/compose:1.26.2'
    dir: $_DIR
    args: ['-f', 'docker-compose.yaml', 'run', 'app']
    env:
      - COMPOSE_DOCKER_CLI_BUILD=1

substitutions:
  _DIR: cache-from-compose
