steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: [
      '-c',
      'gcloud secrets versions access latest --secret=git-credentials > .git-credentials'
    ]

  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/pokutuna/cloudbuild-playground.git']

  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    entrypoint: bash
    args:
      - '-c'
      - |
        git config --local user.name pokutuna-bot
        git config --local user.email bot@pokutuna.com
        git config --local credential.helper 'store --file /workspace/.git-credentials'

  - name: alpine
    entrypoint: sh
    args: ['-c', 'echo 1 > /workspace/$_DIR/some_file']

  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    entrypoint: bash
    args:
      - '-c'
      - |
        git diff --quiet some_file || git commit -m 'Update some_file' some_file

  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    args: ['log']

  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    args: ['push', 'origin', 'HEAD:$BRANCH_NAME']

substitutions:
  _DIR: cloudbuild-playground/git-push
