steps:
  # Get credentials from Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=deploy-key-cloudbuild-playground > /root/.ssh/id_github'

  # Set up ssh
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_github
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_github
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts

  # Clone the repository.
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'git@github.com:pokutuna/cloudbuild-playground.git']

  # Set git configs to commit files.
  # Use `--local` to store into .git/config.
  # $HOME/.gitconfig is not under the `/workspace` directory.
  # (Or mount & keep the config as global.)
  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    entrypoint: bash
    args:
      - '-c'
      - |
        git config --local user.name pokutuna-bot
        git config --local user.email bot@pokutuna.com
        git config --local credential.helper 'store --file /workspace/.git-credentials'

  # Update file.
  - name: alpine
    entrypoint: sh
    args:
      - '-c'
      - 'echo 2 > /workspace/$_DIR/some_file'

  # Do `git commit` if the file changed.
  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    entrypoint: bash
    args:
      - '-c'
      - git diff --quiet some_file || git commit -m 'Update some_file' some_file

  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    args: ['log']

  - name: gcr.io/cloud-builders/git
    dir: $_DIR
    args: ['push', 'origin', 'HEAD:$BRANCH_NAME']

options:
  - name: ssh
    path: /root/.ssh

substitutions:
  _DIR: cloudbuild-playground/git-push
