steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/pokutuna/cloudbuild-playground.git']

  - name: gcr.io/cloud-builders/git
    dir: cloudbuild-playground
    entrypoint: bash
    args:
      - '-c'
      - |
        git config --local user.name pokutuna-bot
        git config --local user.email bot@pokutuna.com

  - name: alpine
    entrypoint: sh
    args: ['-c', 'echo 1 > /workspace/cloudbuild-playground/some_file']

  - name: alpine
    dir: 'cloudbuild-playground'
    entrypoint: cat
    args: ['some_file']

  - name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-playground'
    args: ['ls-files']

  - name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-playground'
    args: ['status']

  - name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-playground'
    entrypoint: bash
    args:
      - '-c'
      - |
        git diff --quiet some_file || git commit -m 'Update some_file' some_file
  - name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-playground'
    args: ['log']
